// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.layout.display-list.retain", true);
user_pref("app.normandy.startupRolloutPrefs.security.tls.version.fallback-limit", 4);
user_pref("app.normandy.user_id", "5ac066c0-2816-42eb-a944-eb9ce794deca");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1548886445);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1548886565);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1548900461);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1548886325);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1548886205);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1548886805);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1548886685);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1548886054);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"32907\":1548893389824,\"32955\":1548893389824,\"32980\":1548893389824}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{dac4d285-9906-4334-83be-c7a90f213949}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1548835200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1548893390);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1548900503732");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1548902315732");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1548900440741");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1548904040741");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180704194950");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1548893390");
user_pref("browser.slowStartup.averageTime", 2935);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20180704194950");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1548886061480");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Mon, 28 Jan 2019 18:12:57 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1548886447);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180704194950");
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"4dcca6a8-fbfe-4e60-a737-304c5dab59a8\",\"screenshots@mozilla.org\":\"fff17036-35a9-4bfd-9e0d-e698e52d1f73\"}");
user_pref("idle.lastDailyNotification", 1548892241);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1548886448);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180704194950");
user_pref("media.gmp-manager.lastCheck", 1548886636);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1548892242);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "1d5b3fb5-efcc-44ae-a471-dedbdb33a445");
user_pref("services.blocklist.addons.checked", 1548886512);
user_pref("services.blocklist.gfx.checked", 1548886512);
user_pref("services.blocklist.onecrl.checked", 1548886512);
user_pref("services.blocklist.pinning.checked", 1548886512);
user_pref("services.blocklist.plugins.checked", 1548886512);
user_pref("services.settings.clock_skew_seconds", 52);
user_pref("services.settings.last_etag", "\"1548796224519\"");
user_pref("services.settings.last_update_seconds", 1548886512);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1548892242);
user_pref("toolkit.startup.last_success", 1548893386);
user_pref("toolkit.telemetry.cachedClientID", "8c832055-088a-47e4-83cd-6a5817ffbc43");
user_pref("toolkit.telemetry.previousBuildID", "20180704194950");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
